- name: ensure fonts directory
  tags:
    - fonts
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Fira Code exists
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
  register: hack_exists
  ignore_errors: yes
  tags:
    - fonts

- name: Download Hack
  when: hack_exists is failed
  tags:
    - fonts
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FiraCode.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes

- name: Download Jetbrains Mono
  tags:
    - fonts
    - jetbrainsmono
  ansible.builtin.unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes
