- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/node.yml
    - include: tasks/nvim.yml
    - include: tasks/alacritty.yml
    - include: tasks/fonts.yml
    - include: tasks/docker.yml
    - include: tasks/php.yml

